### ISSUE TITLE
[RAID] Information about pre nerf state of Karazhan

### ISSUE THREAD

**Issue by descendance** [Schaka/TBC-research#4]
I made [this post](http://forum.wow-hellground.com/index.php?/topic/95-information-about-pre-nerf-karazhan/#comment-297) on hellground forums about karazhan pre nerf, hope it can help some people. 
Thught about posting the whole thing here, but i cant get the same text formatting to work here(with all the nice colors and spoilers whooosh  :dancer: ).  Right now the formatting is kinda wonky on their website will see if it can be fixed, also seems i will need to replace all the hgdatabase links becouse that is updated also with their switch, but you can still use it.
What needs to be done, is maybe one of the hardcore guild can run Karazhan on corecraft and compare with the values in the post.(dunno if that is ok, but saw KimmoKM posts here so i guess it's ok with shiro/nim?)

I also made a post about pre nerf heroics on gummy's forums a while back, but it is not as detailed as the karazhan one, but maybe it can help some people out. [PART I](https://www.burning-crusade.com/forums/index.php/topic/932-information-about-pre-nerf-dungeons-part-i/)  and [PART II](https://www.burning-crusade.com/forums/index.php/topic/934-information-about-pre-nerf-dungeons-part-ii/). 

So here is for hopping that this helps future research, and also more people join in on the fun.
It's been 10 years and we still have no detail research online, kinda disappointing from the community as a whole.

**Comment by KimmoKM** [comment]
> What needs to be done, is maybe one of the hardcore guild can run Karazhan on corecraft and compare with the values in the post.(dunno if that is ok, but saw KimmoKM posts here so i guess it's ok with shiro/nim?)

It didn't even occur to me to ask but now that you posted this, I did ask shiro about it. He gave it an a-ok.

> 12:28:11 <KimmoKM> Just to inform you, I'm going to go through instances on the test server and record the values mobs have because, as far as I can tell, they tend to be substantiated by research and are better than guessed numbers in 
> open source emulation. The final goal of course isn't to make CC-like server (I've already found more precise numbers for a few mobs) but it seems like a good starting point since I can do 
> 12:28:11 <KimmoKM> it with little effort.
> 12:28:39 <KimmoKM> I hope that's all right with you
> 12:32:54 <KimmoKM> (record==let mobs hit me and figure out the damage ranges that way, I'm not going to try to steal the databases themselves or anything)
> 22:50:04 <shiroppu> sure, any testing based research on our server is inevitable

Since I have a GM account, it's pretty easy for me to run through the instance naked with a billion health and get the damage ranges from Recount. Going into greater detail than that (like testing ability targeting or timers or whatever) is a bit different because at that point you might as well start consulting primary sources. The goal isn't to make CC-like servers, it's just that Corecraft values have been proven to be substantiated by research in the past so they are preferable to pure guesses you see in open source emulation. Ideally you'd have all of the values sourced to retail evidence.

**Comment by descendance** [comment]
Well that's great to hear. Maybe you will be able to test karazhan and compare to the values i made in that post. It's not perfect and someone already pointed out some mistakes, but you can use it as a starting point for finding correct values for hp/dmg :smile:

**Comment by Evolvee** [comment]
@KimmoKM 

>  it's just that Corecraft values have been proven to be substantiated by research in the past so they are preferable to pure guesses you see in open source emulation. 

**Thanks very much for doing this**, but can I ask you, are you going to upload the current values which are currently on corecraft (with inflated HP sometimes) or the raw ones after removing the inflation? 
I think its not a secret anymore that bosses like Moroes have around +20-25% inflated HP, probably in order to compensate for 2.4.3 talents/items/knowledge of ppl in 2017. Or is this all legit based on research that we will never ever be able to see ourself?(sources that dont exist anymore)... I know that Karazhan was on retail changing almost every week but I mean... I dont want to sound rude but I tried to find a source that would confirm the HP corecraft had, but I didnt find anything... Instead, I most likely found a pattern that just multiplies HP of a certain level creature(lets say 73 level mob base HP x Y multiplier)--> exactly how blizzard is doing it as well when it comes to determination of boss HP values.

The reason why I´m asking this is because most of projects that are aiming for pre-nerf PVE are going to inflate/boost the raids anyway after implementing them to retail shape. So that way they could prevent boosting them 2x more which would essentially made them unkillable... Corecraft PVE was considered to be very well balanced....

**Comment by KimmoKM** [comment]
The values that are on the server right now. As I've said previously, they should be treated as "educated guess" values (unless otherwise mentioned) that likely have some basis on retail evidence but should never be taken as proof of retail functionality at any state of the game.

In some cases the HP does appear inflated. I haven't personally looked hard enough into it to have found a pattern but a few mobs/bosses I've looked at (like High King Maulgar and his adds) had higher HP than any values I've found and HP appears not to have been something that Blizzard used to tweak much. At that time I just thought they had pre-pre-pre nerf evidence I wasn't aware of but maybe there was a systematic increase, I've got to ask Shiro about that. Or who really knows - the week 1 state of the encounters is extremely poorly documented like you said and Blizzard did tweak the encounters on fly. If you want to err in the side of caution and be sure not to buff anything beyond the least nerfed retail version, it's probably safer to just use 2.4.3 values that are well-documented (with an exception of well-known HP changes like M'uru, although that particular example of course isn't within the scope of CC research).

Damage ranges are a bit different matter because it's almost impossible to figure the exact values in most cases to begin with and my methodology can be a few percent off in determining the values Corecraft has on top of that. However, in this case I haven't found anything that is clearly wrong while open source emulation (and servers that haven't changed those values) can even be wrong by a factor of 10 so anything in the correct order of magnitude is an improvement. For example, if you look at a mob like Shadowmoon Adept in [database](https://www.burning-crusade.com/database/?npc=18615) hosted by Burning-Crusade (I assume it's stock-DB values as opposed to showing their original work), it's listed as having 402-908 damage. However, Wowhead provides a [source](http://www.wowhead.com/npc=17397/shadowmoon-adept#comments:id=49555) to damage as high as 4700-7000 (against what probably was around 10% armour). Corecraft test server damage range was actually slightly less (I think it was something like 4000-6000 but I didn't write it down because I already found that more reliable source). CC was demonstrably wrong (in this case undertuned) but using their values sure as hell would have been closer to truth than leaving them as-is or making up something that "feels right" (because a seemingly random humanoid trash mob that even looks like a caster being capable of dealing 21k damage instantly would seem off if you didn't know any better)

With that in mind, until (damage) values backed up by primary sources are found, you're probably better off going with the ones from CC test server. That's my thinking, anyway. Since you've apparently noticed a systematic x% increase in HP values, I think I'll just remove HP/mana values if they seem to follow such pattern. Immunity masks (which descendance appears to have sourced to Wowhead etc pretty well) and damage are the more relevant parts in trying to re-implement the pre-nerf state anyway.

**Edit**
Having just recorded CC values from Magtheridon, I took a look at [video](https://www.youtube.com/watch?v=A5Ma8G8ZScc) from Curse which appears to have been the fourth kill in the world. Health on channellers checks out but Maggy himself appears to have received +30% buff on CC. However, both Maggy and channellers appear to have been nerfed since (channellers quite dramatically) so 2.4.3 values wouldn't be right either.

I'll look closer into this. Perhaps ALL raid bosses have +30% health and adds/trash don't have any custom buffs (I checked all heroic bosses and they had their 2.4.3 values as-is and at least Maggy adds were unbuffed relative to pre-nerf evidence), in which case it would be easy to just slice 30% off CC boss health numbers and list that, leaving the table with values that can be presumed to be correct for pre-nerf (supposing Shiro/NiM did their research right).

**Edit 2**
Morogrim Tidewalker appears to have had 30% health buff (compared to a video of world 5th [Morogrim Tidewalker](https://www.youtube.com/watch?v=CgaZjrq_W9w)) while Hydross and High King Maulgar with his posse are +40% (compared to world [6th Hydross](https://www.youtube.com/watch?v=sqjCkoQxxLU) and [world 10th Maulgar](https://www.youtube.com/watch?v=3yDqIPuxiaY)). On the other hand, Hydross video happens to show health on the water elementals before pull and that checks out.

So yes, looks like bosses tend to have a flat percentage of health increase (although the amount depends on case-by-case basis). For trash, adds and 5-man mobs I feel confident in assuming there's no custom tuning involved (although I'll be sure to check if it appears there might be, on Curator orbs for instance). To make the answer to the original question clear, the values I'm going to list won't include these custom buffs.

**Comment by Evolvee** [comment]
Nice! I think it wouldnt be bad to list even these CC values since their PVE was considered to be very good and I guess they had a reason for doing this... so other projects can know how much they can inflate it and where is the reasonable border which shouldnt be crossed...

**Comment by Schaka** [comment]
I'm not entirely sure they are custom buffs. I remember reading in the beginning of research on IRC, a good 5 years back or so, that they had evidence a lot of bosses were nerfed while guilds still attempted to kill them. This may have only been true for Karazhan though. 

If this also happened to T5 content, there is a possibility CC HP values aren't a flat 30% HP buff but rather, they had evidence of buffs that occured as guilds were still wiping. If there are some extremely early **attempt** videos out there, they might be realiable information.

**Comment by Evolvee** [comment]
Yea I would rather take what CC had because it was doable and at the same time challenging. I heard that T5 received nerfs before anyone even stepped into it. And then it was pretty much changed every few days.
I was told that CC test guilds made some research document with all the changes and research. That document then was ment to be released on CC´s release date in order to let guilds know what they are going into... 
It was a work of many ppl and I was told that they can´t share it without permission of all of them(which is atm impossible).

Pre-nerf PVE sources that existed back in 2012(which were even at that time very rare and mostly deleted as well) dont exist anymore so its kinda waste of time even searching for it in 2017 and the only "semi-reliable" way to get to atleast approximate values is to use what CC has atm...

**Comment by KimmoKM** [comment]
That's of course possible. The values for bosses mentioned above at least are exactly 30/40% but then again, you didn't have exact HP display in TBC so it's plausible there is or used to be some pre-world first evidence that shows the bosses involved had more health than what's seen in those top10 kill videos I was able to find quickly, and devs picked a nice round number that is at least closer to the pre-pre-pre nerf values than the ones Blizzard eventually settled to. I included CC-like values for Maggy because might as well. I'll probably continue with Coilfang instances tomorrow and will do the same for SSC bosses in case there's a difference between CC values and ones I can verify.

**Comment by Aprics** [comment]
I heard Shiro talk about nerfs on the whole Raid content (Blanket nerf) by Blizzard in early days of TBC. Like you said on CC there seems to be a lot of estimations involved in the HP of bosses which is hard to justify without credible source of that number or a huge known rework that some bosses like Morogrimm got.
I think most servers who want to take those values from CC should just adjust them for unclarified boss HP to their own values as long as they seem plausible. Noting it down on their individual forums might be a good idea.

**Comment by kelno** [comment]
This issue was moved to kelno/TBC-research#5
